baseURL = "www.oxxodata.com"
languageCode = "fr-fr"
title = "OXXODATA"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    desktop = "images/logo/logo.png"
    desktop_height = "36px"
    alt = "OXXODATA"

  [params.homepage_meta_tags]
    meta_description = "OXXODATA vous proposes des solutions de télétravail sécurisé et efficace."
    meta_og_title = "OXXODATA"
    meta_og_type = "website"
    meta_og_url = "https://stoic-payne-ef201f.netlify.app/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "OXXODATA vous proposes des solutions de télétravail sécurisé et efficace."
    meta_twitter_card = "summary"
    meta_twitter_site = "@oxxodata"
    meta_twitter_creator = "@oxxodata"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '<a class="zerostatic" href="https://www.oxxodata.com">OXXODATA | Solution cloud, digitalisation et infogérance </a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
