baseURL = "www.oxxodata.com"
languageCode = "fr-fr"
title = "OXXODATA"
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Services"
url = "/services/"
weight = 3
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.footer]
copyright_text = "<a class=\"zerostatic\" href=\"https://www.oxxodata.com\">OXXODATA | Solution cloud, digitalisation et infogérance </a>"
[params.homepage]
hide_view_all_services = false
show_call_box = true
[params.homepage_meta_tags]
meta_description = "OXXODATA vous proposes des solutions de télétravail sécurisé et efficace."
meta_og_description = "OXXODATA vous proposes des solutions de télétravail sécurisé et efficace."
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "OXXODATA"
meta_og_type = "website"
meta_og_url = "https://stoic-payne-ef201f.netlify.app/"
meta_twitter_card = "summary"
meta_twitter_creator = "@oxxodata"
meta_twitter_site = "@oxxodata"
[params.logo]
alt = "OXXODATA"
desktop = "images/logo/logo.png"
desktop_height = "16px"
mobile = "images/logo/logo-mobile.png"
[params.team]
summary_large_truncate = 120
